TrackingSite/TrackingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.views.generic import TemplateView
from .views import home, send_push
from django.conf import settings
from django.conf.urls.static import static
from payments.tasks import lessons_for_week
from background_task.models import Task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payments/', include('payments.urls')),
    url(r'^webpush/', include('webpush.urls')),
    path('', home),
    path('send_push', send_push),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))            
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lessons_for_week(repeat=Task.WEEKLY)


TrackingSite/payments/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url
from . import views

# Namespace all url related to 'payments'
app_name = 'payments'

urlpatterns = [
    # /payments/
    path('', views.IndexView.as_view(), name='index'),
    path('family/', views.FamilyList.as_view(), name='family'),
    path('family/<int:pk>', views.FamilyDetail.as_view(), name='family-detail'),
    path('family/add/', views.FamilyCreate.as_view(), name='family-add'),
    path('family/<int:pk>/update', views.FamilyUpdate.as_view(), name='family-update'),
    path('family/<int:pk>/delete', views.FamilyDelete.as_view(), name='family-delete'),
    path('family/<int:pk>/lessons', views.manage_lessons, name='lessons'),
    path('push/', views.push_test, name='push'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<int:pk>/', views.LessonUpdate.as_view(), name='lesson-update'),      
]

TrackingSite/payments/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import AbstractUser
import datetime

class Family(models.Model):
    client_name = models.CharField(max_length=100)
    student_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    price = models.IntegerField(default=40)
    starting_date = models.DateTimeField()
    balance = models.IntegerField(default=0)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        null=True, 
        blank=True, 
        on_delete=models.CASCADE,
    )

    # Displays as: Family (Student)
    def __str__(self):
        return self.client_name + " (" + self.student_name + ")"

    def update(self):
        new_balance = 0
        for lesson in self.lesson_set.all():
            lesson.save()
            new_balance += lesson.lesson_balance
        self.balance = new_balance

    # Testing
    def create_first_lesson(self):
        if not self.lesson_set.all():
            lesson = Lesson(family=self, appt_date=self.starting_date)
            lesson.save()

    def get_absolute_url(self):
        return reverse('payments:family')
    
    # Override the default Django save() method
    def save(self, *args, **kwargs):        
        self.update()
        super().save(*args, **kwargs)  # Call the "real" save() method.
        self.create_first_lesson()

class Lesson(models.Model):
    family = models.ForeignKey(Family, on_delete=models.CASCADE)    
    appt_date = models.DateTimeField()    

    # Default as 0 instead of family.price or family_price, corrected on save()
    lesson_balance = models.IntegerField(default=0)

    # Defining variables here is good for error prevention and logic seperation
    # https://stackoverflow.com/questions/18676156/how-to-properly-use-the-choices-field-option-in-django
    PAID = 'Paid'
    SKIPPED = 'Skipped'
    PENDING = 'Pending'

    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (PAID, 'Paid'),
        (SKIPPED, 'Skipped'),        
    )

    status = models.CharField(
        max_length=10,        
        choices=STATUS_CHOICES,
        default=PENDING
    )
    
    def update(self):
        if self.status == 'Pending':
            self.lesson_balance = self.family.price
        if self.status == 'Paid':
            self.lesson_balance = 0
        if self.status == 'Skipped':
            self.lesson_balance = 0

    # Call update() on save() by overriding the default Django save() method 
    def save(self, *args, **kwargs):
        self.update()
        super().save(*args, **kwargs)  # Call the "real" save() method.

    # Displays as: Family Name (Child Name) | Date | Status
    def __str__(self):
        str_date = self.appt_date.strftime("%a %d %B %Y")
        name = str(self.family)
        return name + " | " + str_date + " | " + self.status

# Allow future ability to extend default User Model
# See https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project
class CustomUser(AbstractUser):
    pass


TrackingSite/payments/forms.py
from django.forms import ModelForm
from django import forms
from .models import Family, Lesson, CustomUser
from flatpickr import DateTimePickerInput
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class LessonUpdateForm(ModelForm):
    class Meta:
        model = Lesson
        fields = ('appt_date', 'status',)
        widgets = {'appt_date': DateTimePickerInput()}


class FamilyForm(ModelForm):
    class Meta:
        model = Family
        fields = ('client_name', 'student_name', 'address', 'price', 'starting_date', 'balance',)        
        # exclude = ('user',)
        widgets = {'starting_date': DateTimePickerInput()}

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('username',)


TrackingSite/payments/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.forms import inlineformset_factory, widgets
from flatpickr import DateTimePickerInput
from webpush import send_user_notification
from django.conf import settings

from .models import Family, Lesson, CustomUser

from .forms import LessonUpdateForm, FamilyForm, CustomUserCreationForm
from django.contrib.auth.forms import UserCreationForm


class IndexView(generic.ListView):
    model = Family
    template_name = 'payments/index.html'    
    def get_queryset(self):
        # Check to avoid errors on anonymous user aka not logged in
        if self.request.user.is_authenticated:
            return Family.objects.all().filter(user=self.request.user)
    context_object_name = 'families'

# Use mixin to show a ListView of all lessons of a particular Family
class FamilyDetail(SingleObjectMixin, generic.ListView):
    paginate_by = 10
    model = Family    
    template_name = 'payments/family_detail.html'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Family.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['family'] = self.object
        return context

    def get_queryset(self):
        return self.object.lesson_set.all()

class FamilyList(generic.ListView):
    model = Family
    template_name = 'payments/family.html'
    def get_queryset(self):
        # Check to avoid errors on anonymous user aka not logged in
        if self.request.user.is_authenticated:
            return Family.objects.all().filter(user=self.request.user)
    context_object_name = 'families'

class FamilyCreate(LoginRequiredMixin, CreateView):
    form_class = FamilyForm
    model = Family
    template_name = 'payments/family_form.html'  
    # Override form_valid() to automatically assosiate Logged in User with Family    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class FamilyUpdate(LoginRequiredMixin, UpdateView):
    form_class = FamilyForm
    model = Family
    template_name_suffix = '_update_form'
    
class FamilyDelete(LoginRequiredMixin, DeleteView):
    model = Family
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('payments:family')

def manage_lessons(request, pk):
    family = Family.objects.get(pk=pk)    
    LessonInlineFormSet = inlineformset_factory(
                            Family, 
                            Lesson, 
                            fields=('appt_date', 'status',),
                            widgets={'appt_date': DateTimePickerInput()}, 
                            extra=0,
                            can_delete=False)
    if request.method == "POST":
        formset = LessonInlineFormSet(request.POST, request.FILES, instance=family)
        if formset.is_valid():
            formset.save()
            family.save()
            
            return HttpResponseRedirect(reverse_lazy('payments:family-detail', args=(pk,)))
    else:
        formset = LessonInlineFormSet(instance=family)
    return render(request, 'payments/manage_lessons.html', {'formset': formset})

class LessonUpdate(LoginRequiredMixin, UpdateView):
    form_class = LessonUpdateForm
    model = Lesson
    template_name_suffix = '_update_form' 
    success_url = reverse_lazy('payments:index')
    context_object_name = 'lesson'

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def push_test(request):
    webpush_settings = getattr(settings, 'WEBPUSH_SETTINGS', {})
    vapid_key = webpush_settings.get('VAPID_PUBLIC_KEY')
    user = request.user
    return render(request, 'payments/push_template.html', {user: user, 'vapid_key': vapid_key})

# def update_lesson(request, pk):
#     # family = Family.objects.get(pk=pk)
#     lesson = Lesson.objects.get(pk=pk)  
#     if request.method == "POST":
#         form = LessonUpdateForm(request.post)
#         if form.is_valid():
#             form.save()            
#             return HttpResponseRedirect(lesson.get_absolute_url())
#     else:
#         form = LessonUpdateForm()
#     return render(request, 'payments/update_lessons.html', {'form': form})

TrackingSite/payments/templates/payments/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags for Bootstrap 4 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Key for Push Notifications-->
    <meta name="vapid-key" content="{{ vapid_key }}">
    {% if user.id %}
        <meta name="user_id" content="{{ user.id }}">
    {% endif %}

    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Custom CSS to tweak Bootstrap 4 push content below Navbar -->
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    <title>Payment Tracker</title>
    {% block header %}
        <!-- Header content -->
    {% endblock header %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'payments:index' %}">Payment Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
              
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'payments:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'payments:family' %}">Families</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#"">Disabled</a>
                </li> -->
                
            </ul>
            <!-- Change to Login/Logout -->
            {% if user.is_authenticated %}
                <div class="navbar-text">
                    Hello, {{ user.username }}!                    
                    <small> 
                        <a href="{% url 'logout' %}" class="text-secondary">logout</a>
                    </small>
                </div>    
                    
            {% else %}
            
                <div class="navbar-text">                                   
                    <a href="{% url 'login' %}">Login</a>
                    <a> | </a>
                    <small>
                        <a href="{% url 'payments:signup' %}" class="font-weight-light">Register</a>
                    </small>
                </div>  
            {% endif %}
            
        </div>
    </nav>
              
   
    {% block content %}
        <!-- Extended content goes here! -->
    {% endblock content %}


    <!-- Bootstrap 4 JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>
    


TrackingSite/payments/templates/payments/family.html
{% extends 'payments/base.html' %}
{% block content %}
<div class="container"><h1>Family</h1>



    <a href="{% url 'payments:family-add' %}">Add new Family</a>
    <ul>
    {% for family in object_list %}
        <li>
            <p>
                {{ family }}: 
                <a href="{% url 'payments:family-detail' family.id %}">View</a> 
                <a href="{% url 'payments:family-update' family.id %}">Update</a> 
                <a href="{% url 'payments:family-delete' family.id %}">Delete</a>
            </p>
        </li>
        
        
    {% empty %}
        <li>No familys yet.</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}


TrackingSite/payments/templates/payments/family_confirm_delete.html
{% extends 'payments/base.html' %}
{% block content %}
<div class="container">
        <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input type="submit" value="Confirm">
            </form>
</div>
{% endblock %}



TrackingSite/payments/templates/payments/family_detail.html
{% extends 'payments/base.html' %}
{% block content %}
<div class="container">
  <h1>{{ object }}</h1>
  <p>
    Balance: {{ object.balance }}
    <br>
    Charging: {{ object.price }}
    <br>
    Lessons on {{ object.starting_date|date:"l"}} at {{ object.starting_date|time:"g:i a" }}
    <br>
    Location: {{ object.address }}
  </p>


  <h2>Lessons</h2>
  <a href="{% url 'payments:lessons' object.id %}">Change lesson Status</a>
  <ol>
    {% for lesson in page_obj %}
    <li>{{ lesson }}</li>
    {% endfor %}
  </ol>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      {% endif %}
    </span>
  </div>


  <p>
    <a href="{% url 'payments:family-update' object.id %}">Update</a>
    <br>
    <a href="{% url 'payments:family-delete' object.id %}">Delete</a> (Cannot be undone!)
  </p>

</div>
{% endblock %}

TrackingSite/payments/templates/payments/family_form.html
{% extends 'payments/base.html' %}
{% block content %}
<div class="container">
        <form method="post">{% csrf_token %}
                {{ form.media.css }}
                {{ form.media.js }}
                {{ form.as_p }}
                <input type="submit" value="Save">
            </form>
</div>
{% endblock %}


TrackingSite/payments/templates/payments/family_update_form.html
{% extends 'payments/base.html' %}
{% block content %}
{{ form.media.css }}
{{ form.media.js }}
<div class="container">
        <form method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                
                <input type="submit" value="Update">
            </form>
</div>
{% endblock %}



TrackingSite/payments/templates/payments/index.html
{% extends 'payments/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="row">
    <div class="col">
        <ul>
            {% for family in object_list %}
                <li>{{ family }} has a balance of ${{ family.balance }}</li>
            {% empty %}
                <li>No familys yet.</li>
            {% endfor %}
        </ul>
    </div>
    
    <!-- Testing Web Push -->
    <!-- <div class="col">
            <form id="send-push__form">
                    <div class="form-group">
                        <h3 class="header">Send a push notification</h3>
                        <p class="error"></p>
                        <input type="text" name="head" placeholder="Header: Your favorite airline 😍">
                    </div>
                    <div class="form-group">
                        <textarea name="body" id="" cols="30" rows="10" placeholder="Body: Your flight has been cancelled 😱😱😱"></textarea>
                    </div>        
                    <div class="form-group">
                        <button>Send Me</button>
                    </div>
                </form>
    </div>
</div>   -->
      
</div>
    <script src="{% static '/js/registerSw.js' %}"></script>
    <script src="{% static '/js/site.js' %}"></script>

{% endblock %}



TrackingSite/payments/templates/payments/lesson_update_form.html
{% extends 'payments/base.html' %}
{% block content %}


<div class="container">
        {{ lesson.family }}
        <form method="post">
                {% csrf_token %}
                {{ form.media.css }}
                {{ form.media.js }} 
                {{ form.as_table }}
                <p><input type="submit" value="Update"></p>
            </form> 
</div>
{% endblock %}


TrackingSite/payments/templates/payments/manage_lessons.html
{% extends 'payments/base.html' %}
{% load static %}
{% block content %}

<div class="container">
        <form method="post">             
                {{ formset.management_form }}
                {% for form in formset %}
                    {% csrf_token %}
                    {{ form.media.css }}
                    {{ form.media.js }}                                      
                    {{ form.as_p }}                                                  
                {% endfor %}
                <input type="submit" value="Update">
            </form>            
</div>
{% endblock %}



TrackingSite/payments/templates/payments/push_template.html
{% extends 'payments/base.html' %}
{% load webpush_notifications %}

{% block header %}
    {% webpush_header %}
{% endblock %}        

{% block content %}
    <p> Please subscribe to get Push Notifications </p>    
    {% webpush_button %}
{% endblock %}