TrackingSite/TrackingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.views.generic import TemplateView
from .views import home, send_push
from django.conf import settings
from django.conf.urls.static import static
from payments.tasks import lessons_for_week
from background_task.models import Task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payments/', include('payments.urls')),
    url(r'^webpush/', include('webpush.urls')),
    path('', home),
    path('send_push', send_push),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))            
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lessons_for_week(repeat=Task.WEEKLY)


TrackingSite/payments/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url
from . import views

# Namespace all url related to 'payments'
app_name = 'payments'

urlpatterns = [
    # /payments/
    path('', views.IndexView.as_view(), name='index'),
    path('family/', views.FamilyList.as_view(), name='family'),
    path('family/<int:pk>', views.FamilyDetail.as_view(), name='family-detail'),
    path('family/add/', views.FamilyCreate.as_view(), name='family-add'),
    path('family/<int:pk>/update', views.FamilyUpdate.as_view(), name='family-update'),
    path('family/<int:pk>/delete', views.FamilyDelete.as_view(), name='family-delete'),
    path('family/<int:pk>/lessons', views.manage_lessons, name='lessons'),
    path('push/', views.push_test, name='push'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<int:pk>/', views.LessonUpdate.as_view(), name='lesson-update'),      
]

TrackingSite/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags for Bootstrap 4 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Key for Push Notifications-->
    <meta name="vapid-key" content="{{ vapid_key }}">
    {% if user.id %}
        <meta name="user_id" content="{{ user.id }}">
    {% endif %}

    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Custom CSS to tweak Bootstrap 4 -->
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    <title>Payment Tracker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'payments:index' %}">Payment Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
              
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'payments:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'payments:family' %}">Families</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#"">Disabled</a>
                </li> -->
                
            </ul>
            <!-- Change to Login/Logout -->
            {% if user.is_authenticated %}
                <div class="navbar-text">
                    Hello, {{ user.username }}!                    
                    <small> 
                        <a href="{% url 'logout' %}" class="text-secondary">logout</a>
                    </small>
                </div>    
                    
            {% else %}
            <!-- <div class="login-container">
                {% csrf_token %}
                <form action="{% url 'login' %}">
                  <input type="text" placeholder="Username" name="username">
                  <input type="password" placeholder="Password" name="psw">
                  <button type="submit">Login</button>
                </form>
              </div>  -->
                <div class="navbar-text">                                   
                    <a href="{% url 'login' %}">Login</a>
                    <a> | </a>
                    <small>
                        <a href="{% url 'payments:signup' %}" class="font-weight-light">Register</a>
                    </small>
                </div>  
            {% endif %}
            
        </div>
    </nav>
              
   
    {% block content %}
        <!-- Extended content goes here! -->
    {% endblock content %}


    <!-- Bootstrap 4 JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>
    


TrackingSite/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'payments:signup' %}">signup</a>
{% endif %}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="vapid-key" content="{{ vapid_key }}">
    {% if user.id %}
    <meta name="user_id" content="{{ user.id }}">
    {% endif %}
    <title>Web Push</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700" rel="stylesheet">
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div>
        <form id="send-push__form">
            <h3 class="header">Send a push notification</h3>
            <p class="error"></p>
            <input type="text" name="head" placeholder="Header: Your favorite airline 😍">
            <textarea name="body" id="" cols="30" rows="10"
                placeholder="Body: Your flight has been cancelled 😱😱😱"></textarea>
            <button>Send Me</button>
        </form>
    </div>
    <script src="{% static '/js/registerSw.js' %}"></script>
    <script src="{% static '/js/site.js' %}"></script>
</body>

{% endblock %}

TrackingSite/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}